---

vagrant: false

ntp:
  - '216.239.35.8'

timezone: Etc/UTC

clag_pairs:
  edge:
    - edge-1
    - edge-2
  wan:
    - wan-1
    - wan-2

ptm:
  - '"wan-1":"swp51" -- "wan-2":"swp51"'
  - '"wan-1":"swp52" -- "wan-2":"swp52"'
  - '"edge-1":"swp53" -- "edge-2":"swp53"'
  - '"edge-1":"swp54" -- "edge-2":"swp53"'
