---

- hosts: edge

  user: '{{ ansible_ssh_user }}'
  become: 'True'
  gather_facts: 'False'

  roles:
    - switchgroups
    - hostname
    - interfaces
    - routing
    - ptm
    - ntp
    - ifplugd
